---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/greetings":
    get:
      summary: list greetings
      responses:
        '200':
          description: successful
  "/api/v1/greetings/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show greeting
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
